version: '3.9'
services:
  video-manager-upgrade:
    image: 'ghcr.io/irohalab/mira-video-manager:${VIDEO_MANAGER_TAG}'
    container_name: 'video-manager-upgrade'
    profiles: [ 'video-manager' ]
    environment:
      APPCONFIG: /etc/mira/config.yml
      ORMCONFIG: /etc/mira/ormconfig.json
    volumes:
      - ${VM_CONFIG_DIR:-./video-manager}/config.yml:/etc/mira/config.yml:ro
      - ${VM_CONFIG_DIR:-./video-manager}/ormconfig.json:/etc/mira/ormconfig.json:ro
    networks:
      - mira
    command: 'npm run migrate:upgrade'

  download-manager-upgrade:
    image: 'ghcr.io/irohalab/mira-download-manager:${DOWNLOAD_MANAGER_TAG}'
    profiles: [ 'download-manager' ]
    container_name: 'download-manager-upgrade'
    environment:
      APPCONFIG: /etc/mira/config.yml
      ORMCONFIG: /etc/mira/ormconfig.json
    volumes:
      - ${DM_CONFIG_DIR:-./download-manager}/config.yml:/etc/mira/config.yml:ro
      - ${DM_CONFIG_DIR:-./download-manager}/ormconfig.json:/etc/mira/ormconfig.json:ro
    networks:
      - mira
    command: 'npm run migrate:upgrade'
  albireo-upgrade:
    image: 'ghcr.io/irohalab/albireo:${ALBIREO_TAG}'
    container_name: 'albireo-server'
    profiles: ['albireo']
    environment:
      PYTHONUNBUFFERED: 1
      PYTHONPATH: '/usr/app'
    # you can comment out this if your reverse-proxy is using the same docker network
#    ports:
#      - ${ALBIREO_PORT:-30001}:5000
    volumes:
      - ${ALBIREO_CONFIG_DIR:-./albireo}/config.yml:/usr/app/config/config.yml:ro
      - ${ALBIREO_CONFIG_DIR:-./albireo}/sentry.yml:/usr/app/config/sentry.yml:ro
      - ${ALBIREO_CONFIG_DIR:-./albireo}/alembic.ini:/usr/app/alembic.ini:ro
#      - ${DOWNLOAD_DATA:-/data/albireo}:/data/albireo:rw
    command: 'alembic upgrade head'
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - mira
networks:
  mira:
    external: true
    name: mira